version: '2'
services:
  stateless:
    image: gcr.io/intense-howl-207913/stateless:v1
  stateful:
    image: gcr.io/intense-howl-207913/stateful:v2
    volumes:
      - ./stateful/tmp:/tmp
  gateway:
    image: gcr.io/intense-howl-207913/gateway:v1
    depends_on:
      - stateful
      - stateless
    ports:
      - "8080:8080"

