apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: stateful
  name: stateful
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: stateful
    spec:
      containers:
      - image: quay.io/rojer1349/stateful
        name: stateful
        resources: {}
        volumeMounts:
        - mountPath: /tmp
          name: stateful-claim0
      restartPolicy: Always
      volumes:
      - name: stateful-claim0
        persistentVolumeClaim:
          claimName: stateful-claim0
status: {}
