kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: stateful-claim
  labels: 
    app: stateful
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard