apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-deployment
  labels:
    app: stateful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful
  template:
    metadata:
      labels:
        app: stateful
    spec:
      containers:
      - name: stateful
        image: gcr.io/intense-howl-207913/stateful:v2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: gce-pd
          mountPath: /tmp
      volumes:
      - name: gce-pd
        gcePersistentDisk:
          pdName: pse-disk 
          fsType: ext4  
