stateful-deployment.yaml docs/concepts/workloads/controllers  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-deployment
  labels:
    app: stateful
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stateful
  template:
    metadata:
      labels:
        app: stateful
    spec:
      containers:
      - name: stateful
        image: gcr.io/intense-howl-207913/stateful:v1
        ports:
        - containerPort: 8080
